# Generated by Django 5.2.1 on 2025-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_alter_autor_options_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
    ]
